version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
      python: '3.12'
    commands:
      - pwd
      - ls
      - echo Printing variables $opensearch_utils_layer_name $pypdf_layer_name $account_id $region 
  build:
    commands:
      - echo build aws4auth xmldict Opensearchpy lambda layer
      - mkdir python
      - python3 -m pip install requests-aws4auth xmltodict opensearch-py pyjwt cryptography --platform manylinux2014_x86_64 --only-binary=':all:' -t python/
      - zip -r aws4auth.zip python
      - aws lambda publish-layer-version --layer-name $opensearch_utils_layer_name --zip-file fileb://aws4auth.zip --compatible-runtimes  python3.12 --region $region --description Boto3,AWSAuth,XMLDict,OpensearchPy
      - rm -rf python aws4auth.zip
  post_build:
    commands:
      - echo Build completed on `date`
      
